version: '3.1'
services:
  web:
    build: .
    platform: linux/x86_64
    # image: odoo:14.0
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    environment:
      - DB_NAME=odoo-test
      - DB_HOST=mydb
      - DB_USER=odoo
      - DB_PASSWORD=myodoo
  mydb:
    image: postgres:13
    environment:
      - POSTGRES_DB=odoo-test
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: